
package BusinessLogic.ESBServiceClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150120.1832
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StartESBService", targetNamespace = "http://SOAPService.BusinessLogic/", wsdlLocation = "http://localhost:8080/TalentoHumano/StartESBService?wsdl")
public class StartESBService_Service
    extends Service
{

    private final static URL STARTESBSERVICE_WSDL_LOCATION;
    private final static WebServiceException STARTESBSERVICE_EXCEPTION;
    private final static QName STARTESBSERVICE_QNAME = new QName("http://SOAPService.BusinessLogic/", "StartESBService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/TalentoHumano/StartESBService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STARTESBSERVICE_WSDL_LOCATION = url;
        STARTESBSERVICE_EXCEPTION = e;
    }

    public StartESBService_Service() {
        super(__getWsdlLocation(), STARTESBSERVICE_QNAME);
    }

    public StartESBService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), STARTESBSERVICE_QNAME, features);
    }

    public StartESBService_Service(URL wsdlLocation) {
        super(wsdlLocation, STARTESBSERVICE_QNAME);
    }

    public StartESBService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STARTESBSERVICE_QNAME, features);
    }

    public StartESBService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StartESBService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StartESBService
     */
    @WebEndpoint(name = "StartESBServicePort")
    public StartESBService getStartESBServicePort() {
        return super.getPort(new QName("http://SOAPService.BusinessLogic/", "StartESBServicePort"), StartESBService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StartESBService
     */
    @WebEndpoint(name = "StartESBServicePort")
    public StartESBService getStartESBServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://SOAPService.BusinessLogic/", "StartESBServicePort"), StartESBService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STARTESBSERVICE_EXCEPTION!= null) {
            throw STARTESBSERVICE_EXCEPTION;
        }
        return STARTESBSERVICE_WSDL_LOCATION;
    }

}
