
package BusinessLogic.SOAPServiceClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150120.1832
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UsersTraining", targetNamespace = "http://SOAPService.BusinessLogic/", wsdlLocation = "http://localhost:8080/TalentoHumano/UsersTraining?wsdl")
public class UsersTraining_Service
    extends Service
{

    private final static URL USERSTRAINING_WSDL_LOCATION;
    private final static WebServiceException USERSTRAINING_EXCEPTION;
    private final static QName USERSTRAINING_QNAME = new QName("http://SOAPService.BusinessLogic/", "UsersTraining");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/TalentoHumano/UsersTraining?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USERSTRAINING_WSDL_LOCATION = url;
        USERSTRAINING_EXCEPTION = e;
    }

    public UsersTraining_Service() {
        super(__getWsdlLocation(), USERSTRAINING_QNAME);
    }

    public UsersTraining_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), USERSTRAINING_QNAME, features);
    }

    public UsersTraining_Service(URL wsdlLocation) {
        super(wsdlLocation, USERSTRAINING_QNAME);
    }

    public UsersTraining_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USERSTRAINING_QNAME, features);
    }

    public UsersTraining_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UsersTraining_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UsersTraining
     */
    @WebEndpoint(name = "UsersTrainingPort")
    public UsersTraining getUsersTrainingPort() {
        return super.getPort(new QName("http://SOAPService.BusinessLogic/", "UsersTrainingPort"), UsersTraining.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UsersTraining
     */
    @WebEndpoint(name = "UsersTrainingPort")
    public UsersTraining getUsersTrainingPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://SOAPService.BusinessLogic/", "UsersTrainingPort"), UsersTraining.class, features);
    }

    private static URL __getWsdlLocation() {
        if (USERSTRAINING_EXCEPTION!= null) {
            throw USERSTRAINING_EXCEPTION;
        }
        return USERSTRAINING_WSDL_LOCATION;
    }

}
